import { 
  LayoutDashboard, 
  Calendar, 
  Users, 
  CreditCard, 
  MessageSquare, 
  Settings, 
  Stethoscope, 
  LogOut,
  Menu,
  X,
  ChevronRight,
  Bell,
  Search,
  User,
  Plus,
  Filter,
  MoreHorizontal,
  CheckCircle2,
  Clock,
  AlertCircle,
  FileText,
  Camera,
  ArrowRight,
  ArrowLeft,
  Home,
  Check,
  Smartphone,
  PieChart,
  BarChart3,
  TrendingUp,
  Wallet,
  Calculator,
  RefreshCw,
  Mail,
  Smartphone as Phone,
  MapPin,
  CalendarDays,
  History,
  ClipboardList,
  Image as ImageIcon,
  CheckSquare,
  Star,
  UserPlus
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Agenda: Calendar,
  Patients: Users,
  Finance: CreditCard,
  Marketing: MessageSquare,
  Settings: Settings,
  Clinical: Stethoscope,
  Logout: LogOut,
  Menu: Menu,
  Close: X,
  ChevronRight: ChevronRight,
  Bell: Bell,
  Search: Search,
  User: User,
  Plus: Plus,
  Filter: Filter,
  More: MoreHorizontal,
  Success: CheckCircle2,
  Pending: Clock,
  Error: AlertCircle,
  Document: FileText,
  Camera: Camera,
  Tooth: Stethoscope, // Fallback for Tooth if not in lucide
  ArrowRight: ArrowRight,
  ArrowLeft: ArrowLeft,
  Home: Home,
  Check: Check,
  Terminal: Smartphone,
  Analytics: PieChart,
  Reports: BarChart3,
  Growth: TrendingUp,
  Wallet: Wallet,
  Calculator: Calculator,
  Sync: RefreshCw,
  Mail: Mail,
  Phone: Phone,
  Location: MapPin,
  CalendarDays: CalendarDays,
  History: History,
  Treatment: ClipboardList,
  Gallery: ImageIcon,
  Checklist: CheckSquare,
  Feedback: Star,
  AddUser: UserPlus
};
